Convert alias to bech32 on return result
chain4travel/magellan pull request #35
Opened 2023-02-07 11:09 UTC by karafyllidis

2023-02-07 11:23 UTC, c4t-ag requested changes

2023-02-07 11:23 UTC, c4t-ag commented on api/v2.go
> +		Key: c.cacheKeyForID("multisig_alias", ownerAddr),
Using bech32 here makes the cache only useable for 1 chain now.
Is there any reason for moving address parsing to GetMSigAlias?

2023-02-07 11:28 UTC, karafyllidis commented on api/v2.go
> +		Key: c.cacheKeyForID("multisig_alias", ownerAddr),
It made more sense to keep the logic there but I understand what you mean. The downside now is that a new cache entry will be created for basically the same data. I will revert the logic like it was in my previous commit.

2023-02-07 13:46 UTC, c4t-ag requested changes
Nice, nearly done 👍 
- pls. clean up (squash) commits
- provide a proper PR description

2023-02-08 09:23 UTC, c4t-ag approved these changes

2023-02-08 09:24 UTC, merged