Control Update Statistics Warning
chain4travel/magellan pull request #63
Opened 2023-05-10 15:05 UTC by jessicaqgomez

## Description
- Added handling of the warning that occurs when the statistics table was going to be updated for the first time

2023-05-11 06:29 UTC, knikos commented
hi @jessicaqgomez can you also include the warning in the description as well as the reason why it's problematic. And also please how your changes solve it. Using the following template questions will be very helpful.

Why this should be merged
How this works
How this was tested

2023-05-11 06:29 UTC, knikos requested changes
hi @jessicaqgomez can you also include the warning in the description as well as the reason why it's problematic. And also please how your changes solve it. Using the following template questions will be very helpful.

Why this should be merged
How this works
How this was tested

2023-05-11 15:42 UTC, jessicaqgomez commented
> hi @jessicaqgomez can you also include the warning in the description as well as the reason why it's problematic. And also please how your changes solve it. Using the following template questions will be very helpful.
> 
> Why this should be merged How this works How this was tested

Ok, i correct the description

2023-05-12 06:36 UTC, knikos approved these changes

2023-05-12 12:55 UTC, merged